name: Sync to all repos

on:
  push:
    branches: [ master ]
    paths-ignore:
      - .github/workflows/sync_to_all_repos.yml
  workflow_dispatch:
    inputs:
      repository:
        description: organization/repository to push
        default: ALL
        required: false

jobs:
  sync-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine single or multi-run
        run: |
          if [ -z "${{ github.event.inputs.repository }}" ] || [ "${{ github.event.inputs.repository }}" == "ALL" ]; then
            echo "Defaulting to multi-repo sync"
            echo "RUN_TYPE=multi" >> $GITHUB_ENV
          else
            echo "Single-repo run: ${{ github.event.inputs.repository }}"
            echo "RUN_TYPE=single" >> $GITHUB_ENV
          fi

      - name: Run sync for all repos
        if: env.RUN_TYPE == 'multi'
        uses: adrianjost/files-sync-action@v1.0.1
        with:
          FILE_PATTERNS: |-
            ^.github/workflows/main.yml
            ^.github/build/get_docker_version.sh
          TARGET_REPOS: |-
            furiousgeorgecontainers/docker-beets-alternative-mod
            furiousgeorgecontainers/docker-calibre-server
            furiousgeorgecontainers/docker-collectd
            furiousgeorgecontainers/docker-cpuload
            furiousgeorgecontainers/docker-elodie
            furiousgeorgecontainers/docker-fever
            furiousgeorgecontainers/docker-leanote
            furiousgeorgecontainers/docker-leanote-populatedb
            furiousgeorgecontainers/docker-matterwiki
            furiousgeorgecontainers/docker-pfsense-backup
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_TOKEN }}

      # Hardcoding the above target repos is less than ideal. Couldn't find a way to read
      # them from an external file...  Will try later.


      - name: Manual sync for one repo
        if: env.RUN_TYPE == 'single'
        uses: adrianjost/files-sync-action@v1.0.1
        with:
          FILE_PATTERNS: |-
            ^.github/workflows/main.yml
            ^.github/build/get_docker_version.sh
          TARGET_REPOS: ${{ github.event.inputs.repository }}
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_TOKEN }}
