name: Sync to all repos

on:
  push:
    branches: [ master ]

jobs:
  sync-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run sync
        uses: adrianjost/files-sync-action@v1.0.1
        with:
          FILE_PATTERNS: |-
            ^.github/workflows/main.yml
            ^.github/build/get_docker_version.sh
          TARGET_REPOS: |-
            furiousgeorgecontainers/docker-elodie
            furiousgeorgecontainers/docker-fever
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_TOKEN }}
